const CartActionTypes = {
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REDUCE_ITEM_QTY: 'REDUCE_ITEM_QTY'
};

export default CartActionTypes;